/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-misused-promises */
/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function seedCategories() {
  const categoryData = [
    { name: "Sports" },
    { name: "Movies" },
    { name: "Books" },
    { name: "Baby" },
    { name: "Health" },
    { name: "Games" },
    { name: "Grocery" },
    { name: "Jewelry" },
    { name: "Electronics" },
    { name: "Shoes" },
    { name: "Computers" },
    { name: "Outdoors" },
    { name: "Tools" },
    { name: "Automotive" },
    { name: "Home" },
    { name: "Clothing" },
    { name: "Kids" },
    { name: "Toys" },
    { name: "Music" },
    { name: "Industrial" },
    { name: "Garden" },
    { name: "Beauty" },
    { name: "Food" },
    { name: "Pets" },
    { name: "Travel" },
    { name: "Art" },
    { name: "Crafts" },
    { name: "Stationery" },
    { name: "Office Supplies" },
    { name: "Fitness" },
    { name: "Watches" },
    { name: "Jackets" },
    { name: "Bags" },
    { name: "Accessories" },
    { name: "Sunglasses" },
    { name: "Hats" },
    { name: "Wallets" },
    { name: "Belts" },
    { name: "Scarves" },
    { name: "Ties" },
    { name: "Dresses" },
    { name: "Skirts" },
    { name: "Jeans" },
    { name: "Trousers" },
    { name: "Shirts" },
    { name: "T-shirts" },
    { name: "Blouses" },
    { name: "Sweaters" },
    { name: "Hoodies" },
    { name: "Jumpsuits" },
    { name: "Swimwear" },
    { name: "Underwear" },
    { name: "Bras" },
    { name: "Pajamas" },
    { name: "Socks" },
    { name: "Leggings" },
    { name: "Jewelry" },
    { name: "Necklaces" },
    { name: "Bracelets" },
    { name: "Rings" },
    { name: "Earrings" },
    { name: "Anklets" },
    { name: "Watches" },
    { name: "Brooches" },
    { name: "Hair Accessories" },
    { name: "Body Jewelry" },
    { name: "Pendants" },
    { name: "Charms" },
    { name: "Keychains" },
    { name: "Mobile Accessories" },
    { name: "Tablet Accessories" },
    { name: "Laptop Accessories" },
    { name: "Computer Components" },
    { name: "Monitors" },
    { name: "Printers" },
    { name: "Networking Equipment" },
    { name: "Storage Devices" },
    { name: "Cables" },
    { name: "Accessories" },
    { name: "Mouse Pads" },
    { name: "Keyboards" },
    { name: "Speakers" },
    { name: "Headphones" },
    { name: "Microphones" },
    { name: "Cameras" },
    { name: "Lenses" },
    { name: "Camera Accessories" },
    { name: "Drones" },
    { name: "Gaming Consoles" },
    { name: "Video Games" },
    { name: "Gaming Accessories" },
    { name: "Controllers" },
    { name: "Virtual Reality Headsets" },
    { name: "Board Games" },
    { name: "Card Games" },
    { name: "Puzzles" },
    { name: "Sports Equipment" },
    { name: "Home Decor" },
    { name: "Pet Supplies" },
    { name: "Travel Accessories" },
  ];

  await prisma.category.createMany({
    data: categoryData,
  });
}

seedCategories()
  .then(() => console.log("Seeding complete"))
  .catch((e) => console.error(e))
  .finally(async () => {
    await prisma.$disconnect();
  });
